version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"  # WebSocket
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  minio:
    image: quay.io/minio/minio:RELEASE.2024-02-24T17-11-14Z
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER:-minioadmin}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:-minioadmin}"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9002:9001"
    volumes:
      - minio_data:/data

  frontend:
    image: ghcr.io/OWNER/esp-frontend:latest
    restart: unless-stopped
    environment:
      NUXT_PUBLIC_MQTT_URL: ${NUXT_PUBLIC_MQTT_URL:-wss://yoowee.ru/mqtt}
    ports:
      - "3000:3000"
    depends_on:
      - mosquitto

volumes:
  mosquitto_data:
  mosquitto_log:
  minio_data:
